name: Release
on:
  push:
    branches: [ 'master' ]

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'staccato_test'
          mysql user: 'staccato'
          mysql password: 'staccato'
      - name: "Install Node.js 14.8.0"
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0
      - name: "Install dependencies"
        run: yarn --frozen-lockfile
      - name: "Run Unit Tests"
        run: yarn test

  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v2
      - name: "Install Node.js 14.8.0"
        uses: actions/setup-node@v1
        with:
          node-version: 14.8.0
      - name: "Install dependencies"
        run: yarn --frozen-lockfile
      - name: "Build artifacts"
        run: yarn build
      - name: "Build docker image"
        run: docker build . -t tarbadev/staccato:0.1.0
      - name: "Upload build folder"
        uses: actions/upload-artifact@v1
        with:
          name: "build"
          path: build

  build-and-push-docker:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "build"
          path: build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tarbadev/staccato:0.1.0

  dev-deploy:
    name: Deploy - Development
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "build"
          path: build
      - name: "Create Google Drive credentials file"
        run: echo "$GOOGLE_DRIVE_SERVICE_ACCOUNT" > build/config/drive-credentials.json
        env:
          GOOGLE_DRIVE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_DEV }}
      - name: "Deploy to dev environment"
        uses: d3sandoval/cloud-foundry-action@1.1.1
        env:
          CF_TARGET_ORG: ${{ secrets.CF_ORG }}
          CF_TARGET_SPACE: "development"
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        with:
          args: "push -f manifest-development.yml"

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: dev-deploy
    steps:
    - uses: actions/checkout@v2
    - name: "Install Node.js 14.8.0"
      uses: actions/setup-node@v1
      with:
        node-version: 14.8.0
    - name: "Install dependencies"
      run: yarn --frozen-lockfile
    - name: "Retrieve DB service key"
      uses: d3sandoval/cloud-foundry-action@1.1.1
      env:
        CF_TARGET_ORG: ${{ secrets.CF_ORG }}
        CF_TARGET_SPACE: "development"
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      with:
        args: "service-key staccato-db e2e_key > /github/workspace/e2e_key.json"
    - name: "Create Google Drive credentials file"
      run: echo "$GOOGLE_DRIVE_SERVICE_ACCOUNT" > config/drive-credentials.json
      env:
        GOOGLE_DRIVE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_DEV }}
    - name: "Run E2E Tests"
      run: |
        DB_CREDENTIALS=$(cat e2e_key.json) \
        yarn test-e2e
      env:
        APP_URL: https://staccato-dev.cfapps.io

  prod-deploy:
    name: Deploy - Production
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "build"
          path: build
      - name: "Create Google Drive credentials file"
        run: echo "$GOOGLE_DRIVE_SERVICE_ACCOUNT" > build/config/drive-credentials.json
        env:
          GOOGLE_DRIVE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS_PROD }}
      - name: "Deploy to Production environment"
        uses: d3sandoval/cloud-foundry-action@1.1.1
        env:
          CF_TARGET_ORG: ${{ secrets.CF_ORG }}
          CF_TARGET_SPACE: "production"
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        with:
          args: "push -f manifest-production.yml"